---
- name: Test Collection Delivery via private_data_dir
  hosts: localhost
  connection: local  # <-- Add this to avoid SSH
  gather_facts: false
  tasks:
    - name: Show ANSIBLE_COLLECTIONS_PATHS from env
      debug:
        msg: "{{ lookup(\"env\", \"ANSIBLE_COLLECTIONS_PATHS\") }}"

    - name: Show ANSIBLE_COLLECTIONS_PATH (singular) from env
      debug:
        msg: "{{ lookup(\"env\", \"ANSIBLE_COLLECTIONS_PATH\") }}"

    - name: List /runner directory
      command: ls -la /runner/
      register: runner_ls
      
    - name: Show /runner contents
      debug:
        var: runner_ls.stdout_lines

    - name: Check if vendor_collections exists
      stat:
        path: /runner/vendor_collections
      register: vendor_stat

    - name: Show vendor_collections stat
      debug:
        var: vendor_stat

    - name: List vendor_collections if it exists
      command: find /runner/vendor_collections -type f
      register: vendor_find
      when: vendor_stat.stat.exists
      ignore_errors: true
      
    - name: Show vendor_collections files
      debug:
        var: vendor_find.stdout_lines
      when: vendor_stat.stat.exists

    - name: Try ansible-galaxy collection list
      command: ansible-galaxy collection list
      register: galaxy_list
      
    - name: Show installed collections
      debug:
        var: galaxy_list.stdout_lines

    - name: Use module from vendor collection
      mytest.verify.hello:
        name: "AAP 2.6 Test"
      register: result

    - name: Display result
      debug:
        msg: "{{ result.message }}"
